- name: Add Application User
  ansible.builtin.user:
    name: "{{app_user}}"

- name: Remove Directory
  ansible.builtin.file:
    path: /app
    state: absent

- name: Add Application Directory
  ansible.builtin.file:
    path: /app
    state: directory

- name: Extracting App Content
  ansible.builtin.unarchive:
    src: https://roboshop-artifacts.s3.amazonaws.com/{{component}}.zip
    dest: /app
    remote_src: yes

