- name: Install Golang
  ansible.builtin.yum:
    name: golang
    state: installed

- name: Import A app_prereq
  ansible.builtin.import_tasks:
    file: app_prereq.yml

# This step is no more needed, as CI pipeline is taking care
- name: Install Golang dependencies
  ansible.builtin.shell: go mod init dispatch ; go get ; go build
  args:
    chdir: /app

- name: Import A schema_setup
  ansible.builtin.import_tasks:
    file: schema_setup.yml

- name: Import A systemd_setup
  ansible.builtin.import_tasks:
    file: systemd_setup.yml