- name: Disable Default Version
  ansible.builtin.shell: dnf module disable nodejs -y

- name: Install Nodejs
  ansible.builtin.shell: dnf module enable nodejs:18 -y

- name: Install Nodejs
  ansible.builtin.yum:
    name: nodejs
    state: installed

- name: Import A app_prereq
  ansible.builtin.import_tasks:
    file: app_prereq.yml

# This step is no more needed, as CI pipeline is taking care
- name: Install NodeJS dependencies
  ansible.builtin.shell: npm install
  args:
    chdir: /app

- name: Import A schema_setup
  ansible.builtin.import_tasks:
    file: schema_setup.yml

- name: Import A systemd_setup
  ansible.builtin.import_tasks:
    file: systemd_setup.yml
