- name: Load Mongodb Schema
  when: schema_setup == "mongo"
  block:
    - name: Copy Mongo Repo
      ansible.builtin.copy:
        src: mongo.repo
        dest: /etc/yum.repos.d/mongo.repo

    - name: Install Mongodb
      ansible.builtin.yum:
        name: mongodb-org-shell
        state: installed

    - name: Load Schema
      ansible.builtin.shell: mongo --host {{ lookup('amazon.aws.aws_ssm', 'catalogue-dev.mongodb_url', region='us-east-1' ) }} </app/schema/{{component}}.js

- name: Load Mysql Schema
  when: schema_setup == "mysql"
  block:
    - name: Install Mysql
      ansible.builtin.yum:
        name: mysql
        state: installed

    - name: Load Schema
      ansible.builtin.shell: mysql -h {{ lookup('amazon.aws.aws_ssm', 'shipping-dev.db_host', region='us-east-1' ) }} -u{{ lookup('amazon.aws.aws_ssm', 'shipping-dev.db_user', region='us-east-1' ) }} -p{{ lookup('amazon.aws.aws_ssm', 'shipping-dev.db_password', region='us-east-1' ) }} < /app/schema/{{component}}.sql